# 尝试执行打印num，捕获Exception 打印异常描述信息
try:
    print(num)
except Exception as result:
    print(result)
